analytics-id: UA-167857042-1
stylesheet: /assets/css/styles.min.css
jsfile: /assets/js/main.min.js
gmap-url: https://www.google.com/maps/d/viewer?mid=
gmap-cid-url: https://maps.google.com/?cid=
images-folder: /assets/images/
test-ind: false
test-date: 20211115
test-time: 1600
match-cvr-img: cvr-ch-1.jpg
bookings-cvr-img: cvr-bd-1.jpg
