name: Trigger Netlify Build
on:
  schedule:
    # # Run at 15:11 & 23:11 daily (UTC -1 = GMT)
    # - cron: '11 15,23 * * *'
    Run at 00:45 on Day 9 of each month (UTC -1 = GMT)
    - cron: '45 00 2 * *'
    # Run at 15:45 on Day 1 of each month (UTC -1 = GMT)
    # - cron: '45 15 1 * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}